"""Alembic environment.

Two settings here are load-bearing:

``render_as_batch=True``
    SQLite cannot ``ALTER TABLE ... DROP COLUMN`` or alter a column type. Batch
    mode emulates those by create-copy-swap. This must be enabled *before the
    first migration is generated* — turning it on later means rewriting the
    migration history (docs/REWRITE_PLAN.md §3.2).

``compare_type`` / ``compare_server_default``
    Without them, autogenerate silently ignores column type changes.

The database URL comes from ``app.core.config`` rather than alembic.ini, so
``DATABASE_URL`` remains the single place the database is named.
"""

from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import pool

from alembic import context
from app.core.config import get_settings
from app.core.db import build_engine

# Importing the models package populates Base.metadata. Without this import,
# autogenerate produces empty migrations.
from app.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _include_object(_object, name, type_, _reflected, _compare_to) -> bool:
    """Keep Alembic's own bookkeeping table out of autogenerated diffs."""
    return not (type_ == "table" and name == "alembic_version")


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting."""
    context.configure(
        url=get_settings().database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=True,
        compare_server_default=True,
        include_object=_include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live connection."""
    connectable = build_engine(poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            compare_type=True,
            compare_server_default=True,
            include_object=_include_object,
        )

        with context.begin_transaction():
            context.run_migrations()

    connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
