from datetime import datetime, timezone

from app.schemas.auth import AuthUser
from app.schemas.students import StudentAcademicHistory, StudentCompliance, StudentProfile


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


USERS: list[dict] = [
    {
        "id": 1,
        "username": "admin",
        "email": "admin@college.edu",
        "first_name": "Super",
        "last_name": "Admin",
        "is_active": True,
        "role": "SUPER_ADMIN",
        "password": "admin1234",
    },
    {
        "id": 2,
        "username": "student",
        "email": "student@college.edu",
        "first_name": "Aarav",
        "last_name": "Patil",
        "is_active": True,
        "role": "STUDENT",
        "password": "student1234",
    },
    {
        "id": 3,
        "username": "tpo",
        "email": "tpo@college.edu",
        "first_name": "Priya",
        "last_name": "Sharma",
        "is_active": True,
        "role": "TPO",
        "password": "tpo12345",
    },
    {
        "id": 4,
        "username": "volunteer",
        "email": "volunteer@college.edu",
        "first_name": "Rohan",
        "last_name": "Joshi",
        "is_active": True,
        "role": "VOLUNTEER",
        "password": "volunteer1234",
    },
]

STUDENTS: list[StudentProfile] = [
    StudentProfile(
        id=1,
        linked_user_id=2,
        full_name="Aarav Patil",
        email="student@college.edu",
        college_roll_no="CSE2023-021",
        admission_year=2023,
        entry_mode="REGULAR",
        program_duration_years=4,
        expected_graduation_year=2027,
        current_academic_year=3,
        status="ACTIVE",
        student_whatsapp_number="+919900000001",
        parent_whatsapp_number="+919900000011",
        parent_email="parent.aarav@example.com",
        date_of_birth="2005-02-14",
        gender="MALE",
        nationality="Indian",
        residential_address="Saraswati Nagar",
        residential_city="Pune",
        pin_code="411001",
        native_place="Satara",
        current_location="Pune",
        branch="Computer Engineering",
        major_minor_subject="AI & DS",
        division="A",
        batch="Batch 1",
        is_active=True,
        academic_history=StudentAcademicHistory(
            tenth_percentage="89.5",
            tenth_year_of_passing=2021,
            tenth_board="State",
            twelfth_or_diploma_type="12TH",
            twelfth_or_diploma_percentage="84.2",
            twelfth_or_diploma_year_of_passing=2023,
            twelfth_board="State",
            btech_sem1_sgpi="8.1",
            btech_sem2_sgpi="8.3",
            se_cgpi="8.2",
            se_percentage="77.9",
            live_kt=0,
            dead_kt=0,
            drop_count=0,
            gap_count=0,
            courses_done_text="Python, SQL",
            internships_text="Summer internship at StartupX",
        ),
        compliance=StudentCompliance(aadhaar_number="123412341234", pan_number="ABCDE1234F"),
        created_at=utc_now_iso(),
        updated_at=utc_now_iso(),
    ),
    StudentProfile(
        id=2,
        linked_user_id=None,
        full_name="Vikram Mehta",
        email="vikram@college.edu",
        college_roll_no="CSE2022-045",
        admission_year=2022,
        entry_mode="REGULAR",
        program_duration_years=4,
        expected_graduation_year=2026,
        current_academic_year=4,
        status="ACTIVE",
        student_whatsapp_number="+919900000002",
        parent_whatsapp_number="+919900000022",
        parent_email="parent.vikram@example.com",
        date_of_birth="2004-05-10",
        gender="MALE",
        nationality="Indian",
        residential_address="Kothrud",
        residential_city="Pune",
        pin_code="411038",
        native_place="Mumbai",
        current_location="Pune",
        branch="Computer Engineering",
        division="B",
        batch="Batch 2, Final Year",
        is_active=True,
        academic_history=StudentAcademicHistory(
            tenth_percentage="88.0",
            tenth_year_of_passing=2020,
            tenth_board="CBSE",
            twelfth_or_diploma_type="12TH",
            twelfth_or_diploma_percentage="82.5",
            twelfth_or_diploma_year_of_passing=2022,
            twelfth_board="State",
            btech_sem1_sgpi="7.8",
            btech_sem2_sgpi="8.0",
            se_cgpi="8.1",
            se_percentage="75.0",
            live_kt=0,
            dead_kt=0,
            drop_count=0,
            gap_count=0,
        ),
        compliance=StudentCompliance(aadhaar_number="234523452345", pan_number="BCDEF2345G"),
        created_at=utc_now_iso(),
        updated_at=utc_now_iso(),
    ),
    StudentProfile(
        id=3,
        linked_user_id=None,
        full_name="Neha Gupta",
        email="neha@college.edu",
        college_roll_no="CSE2024-002",
        admission_year=2024,
        entry_mode="REGULAR",
        program_duration_years=4,
        expected_graduation_year=2028,
        current_academic_year=2,
        status="ACTIVE",
        student_whatsapp_number="+919900000003",
        parent_whatsapp_number="+919900000033",
        parent_email="parent.neha@example.com",
        date_of_birth="2006-09-18",
        gender="FEMALE",
        nationality="Indian",
        residential_address="Aundh",
        residential_city="Pune",
        pin_code="411007",
        native_place="Nagpur",
        current_location="Pune",
        branch="Computer Engineering",
        division="A",
        batch="Batch 1",
        is_active=True,
        academic_history=StudentAcademicHistory(
            tenth_percentage="94.2",
            tenth_year_of_passing=2022,
            tenth_board="CBSE",
            twelfth_or_diploma_type="12TH",
            twelfth_or_diploma_percentage="91.0",
            twelfth_or_diploma_year_of_passing=2024,
            twelfth_board="CBSE",
            btech_sem1_sgpi="9.0",
            btech_sem2_sgpi="9.2",
            se_cgpi="9.1",
            se_percentage="86.0",
            live_kt=0,
            dead_kt=0,
            drop_count=0,
            gap_count=0,
        ),
        compliance=StudentCompliance(aadhaar_number="345634563456", pan_number="CDEFG3456H"),
        created_at=utc_now_iso(),
        updated_at=utc_now_iso(),
    ),
    StudentProfile(
        id=4,
        linked_user_id=None,
        full_name="Aditya Ranade",
        email="aditya@college.edu",
        college_roll_no="IT2021-012",
        admission_year=2021,
        entry_mode="REGULAR",
        program_duration_years=4,
        expected_graduation_year=2025,
        current_academic_year=4,
        status="ALUMNI",
        student_whatsapp_number="+919900000004",
        parent_whatsapp_number="+919900000044",
        parent_email="parent.aditya@example.com",
        date_of_birth="2003-11-20",
        gender="MALE",
        nationality="Indian",
        residential_address="Shivajinagar",
        residential_city="Pune",
        pin_code="411005",
        native_place="Satara",
        current_location="Mumbai",
        branch="Information Technology",
        division="A",
        batch="Batch 1",
        is_active=True,
        academic_history=StudentAcademicHistory(
            tenth_percentage="85.4",
            tenth_year_of_passing=2019,
            tenth_board="State",
            twelfth_or_diploma_type="12TH",
            twelfth_or_diploma_percentage="80.6",
            twelfth_or_diploma_year_of_passing=2021,
            twelfth_board="State",
            btech_sem1_sgpi="7.5",
            btech_sem2_sgpi="7.8",
            se_cgpi="7.9",
            se_percentage="72.0",
            live_kt=0,
            dead_kt=0,
            drop_count=0,
            gap_count=0,
        ),
        compliance=StudentCompliance(aadhaar_number="456745674567", pan_number="DEFGH4567I"),
        created_at=utc_now_iso(),
        updated_at=utc_now_iso(),
    ),
    StudentProfile(
        id=5,
        linked_user_id=None,
        full_name="Sneha Deshmukh",
        email="sneha@college.edu",
        college_roll_no="ETC2023-087",
        admission_year=2023,
        entry_mode="REGULAR",
        program_duration_years=4,
        expected_graduation_year=2027,
        current_academic_year=3,
        status="ACTIVE",
        student_whatsapp_number="+919900000005",
        parent_whatsapp_number="+919900000055",
        parent_email="parent.sneha@example.com",
        date_of_birth="2005-07-22",
        gender="FEMALE",
        nationality="Indian",
        residential_address="Kalyani Nagar",
        residential_city="Pune",
        pin_code="411014",
        native_place="Solapur",
        current_location="Pune",
        branch="Electronics & Telecom",
        division="B",
        batch="Batch 2",
        is_active=False,
        academic_history=StudentAcademicHistory(
            tenth_percentage="78.2",
            tenth_year_of_passing=2021,
            tenth_board="State",
            twelfth_or_diploma_type="12TH",
            twelfth_or_diploma_percentage="74.0",
            twelfth_or_diploma_year_of_passing=2023,
            twelfth_board="State",
            btech_sem1_sgpi="6.2",
            btech_sem2_sgpi="6.0",
            se_cgpi="6.1",
            se_percentage="58.0",
            live_kt=3,
            dead_kt=1,
            drop_count=0,
            gap_count=0,
        ),
        compliance=StudentCompliance(aadhaar_number="567856785678", pan_number="EFGHI5678J"),
        created_at=utc_now_iso(),
        updated_at=utc_now_iso(),
    ),
    StudentProfile(
        id=6,
        linked_user_id=None,
        full_name="Karan Johar",
        email="karan@college.edu",
        college_roll_no="MECH2023-005",
        admission_year=2023,
        entry_mode="REGULAR",
        program_duration_years=4,
        expected_graduation_year=2027,
        current_academic_year=3,
        status="ACTIVE",
        student_whatsapp_number="+919900000006",
        parent_whatsapp_number="+919900000066",
        parent_email="parent.karan@example.com",
        date_of_birth="2005-12-05",
        gender="MALE",
        nationality="Indian",
        residential_address="Hadapsar",
        residential_city="Pune",
        pin_code="411028",
        native_place="Kolhapur",
        current_location="Pune",
        branch="Mechanical Engineering",
        division="A",
        batch="Batch 2",
        is_active=True,
        academic_history=StudentAcademicHistory(
            tenth_percentage="82.0",
            tenth_year_of_passing=2021,
            tenth_board="CBSE",
            twelfth_or_diploma_type="12TH",
            twelfth_or_diploma_percentage="81.2",
            twelfth_or_diploma_year_of_passing=2023,
            twelfth_board="CBSE",
            btech_sem1_sgpi="7.1",
            btech_sem2_sgpi="7.3",
            se_cgpi="7.2",
            se_percentage="68.0",
            live_kt=0,
            dead_kt=0,
            drop_count=0,
            gap_count=0,
        ),
        compliance=StudentCompliance(aadhaar_number="678967896789", pan_number="FGHIJ6789K"),
        created_at=utc_now_iso(),
        updated_at=utc_now_iso(),
    ),
    StudentProfile(
        id=7,
        linked_user_id=None,
        full_name="Pooja Hegde",
        email="pooja@college.edu",
        college_roll_no="IT2023-044",
        admission_year=2023,
        entry_mode="REGULAR",
        program_duration_years=4,
        expected_graduation_year=2027,
        current_academic_year=3,
        status="ACTIVE",
        student_whatsapp_number="+919900000007",
        parent_whatsapp_number="+919900000077",
        parent_email="parent.pooja@example.com",
        date_of_birth="2005-04-18",
        gender="FEMALE",
        nationality="Indian",
        residential_address="Viman Nagar",
        residential_city="Pune",
        pin_code="411014",
        native_place="Pune",
        current_location="Pune",
        branch="Information Technology",
        division="A",
        batch="Batch 3",
        is_active=True,
        academic_history=StudentAcademicHistory(
            tenth_percentage="91.5",
            tenth_year_of_passing=2021,
            tenth_board="CBSE",
            twelfth_or_diploma_type="12TH",
            twelfth_or_diploma_percentage="89.8",
            twelfth_or_diploma_year_of_passing=2023,
            twelfth_board="State",
            btech_sem1_sgpi="8.5",
            btech_sem2_sgpi="8.7",
            se_cgpi="8.6",
            se_percentage="82.0",
            live_kt=0,
            dead_kt=0,
            drop_count=0,
            gap_count=0,
        ),
        compliance=StudentCompliance(aadhaar_number="789078907890", pan_number="GHIJK7890L"),
        created_at=utc_now_iso(),
        updated_at=utc_now_iso(),
    )
]

TOKENS: dict[str, int] = {}
REFRESH_TOKENS: dict[str, int] = {}


def public_user(row: dict) -> AuthUser:
    return AuthUser(
        id=row["id"],
        username=row["username"],
        email=row["email"],
        first_name=row["first_name"],
        last_name=row["last_name"],
        is_active=row["is_active"],
        role=row["role"],
    )


TRAINING_BATCHES: list[dict] = [
    {"name": "Batch 1", "is_active": True},
    {"name": "Batch 2", "is_active": True},
    {"name": "Batch 3", "is_active": True},
    {"name": "Batch 4", "is_active": True},
]

TRAINING_PROGRAMS: list[dict] = [
    {
        "id": 1,
        "name": "Aptitude Foundation",
        "description": "Comprehensive prep on Quantitative Aptitude, Logical Reasoning, and Verbal Ability.",
        "start_date": "2026-06-01",
        "end_date": "2026-06-30",
        "batch": "Batch 1",
    },
    {
        "id": 2,
        "name": "Interview Readiness",
        "description": "Cracking technical rounds, OOP concepts, resume tailoring, and behavioral mock interviews.",
        "start_date": "2026-07-01",
        "end_date": "2026-07-15",
        "batch": "Batch 1",
    }
]

TRAINING_LECTURES: list[dict] = [
    {
        "id": 1,
        "program_id": 1,
        "title": "Quantitative Reasoning: Percentages & Averages",
        "date": "2026-06-02",
        "session_type": "BOTH",
        "batch": "Batch 1",
    },
    {
        "id": 2,
        "program_id": 1,
        "title": "Logical Reasoning: Syllogisms & Blood Relations",
        "date": "2026-06-04",
        "session_type": "BOTH",
        "batch": "Batch 1",
    },
    {
        "id": 3,
        "program_id": 2,
        "title": "Object-Oriented Programming: Inheritance & Polymorphism",
        "date": "2026-07-03",
        "session_type": "BOTH",
        "batch": "Batch 1",
    }
]

TRAINING_ATTENDANCE: list[dict] = [
    {
        "id": 1,
        "lecture_id": 1,
        "student_id": 1,  # Aarav Patil
        "status": "BOTH"
    },
    {
        "id": 2,
        "lecture_id": 2,
        "student_id": 1,  # Aarav Patil
        "status": "MS"  # Morning only
    }
]


